#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : prometheus_client
Version  : 0.4.1
Release  : 5
URL      : https://files.pythonhosted.org/packages/76/e8/b29b8e1dcf176687c30fe39ba9416ffe72fd4254a45ed9f92ecce98278cf/prometheus_client-0.4.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/76/e8/b29b8e1dcf176687c30fe39ba9416ffe72fd4254a45ed9f92ecce98278cf/prometheus_client-0.4.1.tar.gz
Summary  : Python client for the Prometheus monitoring system.
Group    : Development/Tools
License  : Apache-2.0
Requires: prometheus_client-python3
Requires: prometheus_client-python
BuildRequires : buildreq-distutils3

%description
No detailed description available

%package python
Summary: python components for the prometheus_client package.
Group: Default
Requires: prometheus_client-python3 = %{version}-%{release}

%description python
python components for the prometheus_client package.


%package python3
Summary: python3 components for the prometheus_client package.
Group: Default
Requires: python3-core

%description python3
python3 components for the prometheus_client package.


%prep
%setup -q -n prometheus_client-0.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539123691
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
